name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: |
        # install dependencies
        sudo apt-get update
        sudo apt-get install gfortran libsoqt4-dev libmotif-dev
        sudo apt-get install python-matplotlib
        sudo apt-get install texlive transfig
        # compile auto
        ./configure --enable-gui
        make
